[project]
name = "stata-requisitionen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "common",
    "geopandas>=1.1.2",
    "pandas>=2.3.1",
    "pyogrio>=0.12.1",
    "pyproj>=3.7.2",
    "shapely>=2.1.2",
]

[tool.uv.sources]
common = { git = "https://github.com/opendatabs/common", rev = "b2d26f48a7cc43ce823b2763d87c41201e131b40" }
