[project]
name = "stata-requisitionen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.1.2",
    "pandas>=2.3.1",
    "pyodbc>=5.2.0",
    "pyogrio>=0.12.1",
    "pyproj>=3.7.2",
    "python-dotenv>=1.1.1",
    "shapely>=2.1.2",
]
